import { FilterOperator, PaginateConfig } from 'nestjs-paginate';
import { User } from './entites/user.entity';
import { Not } from 'typeorm';

export const USER_PAGINATION_CONFIG: PaginateConfig<User> = {
  defaultSortBy: [['id', 'ASC']],
  searchableColumns: [
    'email',
    'corporate.firstName',
    'corporate.lastName',
    'corporate.gender',
    'corporate.country',
    'corporate.state',
    'corporate.city',
    'corporate.industry',
    'corporate.companyName',
    'corporate.level',
    'corporate.department',
    'corporate.title',
    'muslimCompany.firstName',
    'muslimCompany.lastName',
    'muslimCompany.gender',
    'muslimCompany.country',
    'muslimCompany.state',
    'muslimCompany.city',
    'muslimCompany.industry',
    'muslimCompany.companyName',
    'muslimCompany.level',
    'muslimCompany.department',
    'muslimCompany.title',
    'unemployed.firstName',
    'unemployed.lastName',
    'unemployed.gender',
    'unemployed.country',
    'unemployed.state',
    'unemployed.city',
    'unemployed.fieldOfStudy',
    'unemployed.university',
    'unemployed.lookingFor',
  ],
  sortableColumns: [
    'email',
    'userType',
    'corporate.firstName',
    'corporate.lastName',
    'corporate.gender',
    'corporate.country',
    'corporate.state',
    'corporate.city',
    'corporate.industry',
    'corporate.companyName',
    'corporate.level',
    'corporate.department',
    'corporate.title',
    'muslimCompany.firstName',
    'muslimCompany.lastName',
    'muslimCompany.gender',
    'muslimCompany.country',
    'muslimCompany.state',
    'muslimCompany.city',
    'muslimCompany.industry',
    'muslimCompany.companyName',
    'muslimCompany.level',
    'muslimCompany.department',
    'muslimCompany.title',
    'unemployed.firstName',
    'unemployed.lastName',
    'unemployed.gender',
    'unemployed.country',
    'unemployed.state',
    'unemployed.city',
    'unemployed.fieldOfStudy',
    'unemployed.university',
    'unemployed.lookingFor',
  ],
  ignoreSearchByInQueryParam: true,
  filterableColumns: {
    userType: [FilterOperator.EQ, FilterOperator.IN],
    role: [FilterOperator.EQ, FilterOperator.IN],
    'corporate.firstName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.lastName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.gender': [FilterOperator.EQ],
    'corporate.country': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.state': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.city': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.industry': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.companyName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.level': [FilterOperator.EQ],
    'corporate.department': [FilterOperator.EQ, FilterOperator.ILIKE],
    'corporate.title': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.firstName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.lastName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.gender': [FilterOperator.EQ],
    'muslimCompany.country': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.state': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.city': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.industry': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.companyName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.level': [FilterOperator.EQ],
    'muslimCompany.department': [FilterOperator.EQ, FilterOperator.ILIKE],
    'muslimCompany.title': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.firstName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.lastName': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.gender': [FilterOperator.EQ],
    'unemployed.country': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.state': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.city': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.fieldOfStudy': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.university': [FilterOperator.EQ, FilterOperator.ILIKE],
    'unemployed.lookingFor': [FilterOperator.EQ, FilterOperator.ILIKE],
  },
  relations: {
    corporate: true,
    muslimCompany: true,
    unemployed: true,
  },
  where: {
    role: Not('admin'),
  },
};
